name: model-training

on:
  pull_request:
    branches: master

permissions: write-all

jobs:
  comment_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret 
        run: |
          echo "my secret is \
          ${{ secrets.SuperSecret }}" 
