name: model-training

on:
  pull_request:
    branches: master

permissions: write-all

jobs:
  comment_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret 
        run: |
          echo "the secret1 is \
          ${{ secrets.secret1 }}" 
# add new-secrets and variables in repo setting -> secrets and variables section

      - name: Comment On Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            done! :wave:

